name: Python CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/python.yml'
      - './src/**' 
      - './tst/**'
      
  pull_request:
    branches: [ "master" ]

jobs:
  tdd-katas-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12', '3.11']
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Python with version ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          
      - name: Physics in Python dependencies 
        working-directory: .
        run: poetry install --no-interaction 
      - name: Run tests in physics in Python
        working-directory: .
        run: ./run_tests.sh
        

